config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  get 'periods', to: 'periods#create',as: :periods
  post 'periods',to:'periods#new', as: :periods_new
  get 'periods/view', to:'periods#view', as: :teachers_root

  get 'users/attendence', to:'users#attendence', as: :users_root
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/period.rb
class Period < ApplicationRecord
  
  has_and_belongs_to_many :users, required: false
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :periods, required: false
end

app/controllers/[user]/confirmations_controller.rb
# frozen_string_literal: true

class [user]::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/[user]/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class [user]::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/[user]/passwords_controller.rb
# frozen_string_literal: true

class [user]::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/[user]/registrations_controller.rb
# frozen_string_literal: true

class [user]::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/[user]/sessions_controller.rb
# frozen_string_literal: true

class [user]::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/[user]/unlocks_controller.rb
# frozen_string_literal: true

class [user]::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(user)
    users_root_path
  end
  def after_sign_in_path_for(teacher)
    teachers_root_path
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  def create
    @period=Period.new
  end
  def new
    @period=Period.create(class_date: params[:period][:class_date])

    redirect_to action:"create"
  end
  def view
    @period=Period.order(:class_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:attendence]
  def attendence
    @user=User.find_by(id: current_user.id)
    @today=Period.where(class_date: Time.now.strftime("%a, %d %b %Y ") ).pluck(:class_date).last
    @periods=Period.all.pluck(:class_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>

    <div class="container">
      <div class="jumbotron">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/periods/create.html.erb
<div id="teacher-auth-info-links">
  <%if teacher_signed_in?%>

    <p>
      <%=link_to "Sign Out", destroy_teacher_session_path, method: :delete%>
    </p>
  <%else%>
    <p>
      <%=link_to "Sign In", new_teacher_session_path%>
    </p>
    <p>
      <%=link_to "Sign Up", new_teacher_registration_path%>
    </p>

  <%end%>

</div>

Today: <%=Time.now.strftime("%d/%m/%Y")%>


<%= form_for @period do |f| %>

<div class="form-group col md-6">
  <label for="date">Date</label>
  <%=f.date_field :class_date, placeholder: "Enter the date of class" ,required: "required", class: "form-control here", id:"date"%>

</div>
<button name="submit" type="submit" class="btn btn-success">Add</button>

<%= link_to '<button class="btn btn-primary">View classes</button>'.html_safe, teachers_root_path%>
<%end%>

app/views/periods/view.html.erb
<table>
  <thead>
    <tr>
      <th>Class Dates</th>

    </tr>
  </thead>

  <tbody>
    <% @period.each do |period| %>
      <tr>
        <td><%=period.class_date.strftime("%d-%m-%Y")%></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/users/attendence.html.erb
<div id="auth-info-links">
  <%if user_signed_in?%>

    <p>
      <%=link_to "Sign Out", destroy_user_session_path, method: :delete%>
    </p>
  <%else%>
    <p>
      <%=link_to "Sign In", new_user_session_path%>
    </p>
    <p>
      <%=link_to "Sign Up", new_user_registration_path%>
    </p>

  <%end%>

</div>
<h1>Hello,
  <%=current_user.email%></h1>


  <%if @periods.include? @today%>
    <button class="btn btn-success" id="present">Mark me present</button>
    <%else%>
    <button disabled class="btn btn-success" id="present">Mark me present</button>
    <%end%>

  <button class="btn btn-info" id="present">View my attendance record</button>
  <!-- <%@user.classes=0%> -->

  <script>
    console.log('Script running');
    $('#present').click(function () {

      $(this).prop('disabled', true);

    });
  </script>

app/views/users/attendence.js.erb
console.log('hello');
$('#present').click(function(){
  console.log('iuytiu');
});